### ISSUE TITLE
MSBuild complains about duplicate <ProjectExtensions>tag in AbbreviaD.dproj

### ISSUE THREAD

**Issue by joachimmarder** [TurboPack-Tokyo/Abbrevia#1]
When compiling `Abbrevia.grouproj` on the command line using MsBuild, the following error occurs:

    \\Intranet\Development\Abbrevia10.2\packages\Delphi\AbbreviaD.dproj(682,5): error MSB4079: Das <ProjectExtensions>-Element ist mehrmals vorhanden.

Looking at the file `AbbreviaD.dproj` indeed shows a second but empty `ProjectExtensions` tag on the bottom of the file.

**Comment by romankassebaum** [comment]
Fixed.
